# Generated by Django 3.2.9 on 2021-12-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user_name', max_length=255)),
                ('alias', models.CharField(default='user_alias', max_length=255)),
                ('email', models.EmailField(default='user_email123@gmail.com', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('date_birth', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends_users', models.ManyToManyField(to='friends_app.User')),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_friend', to='friends_app.user')),
            ],
        ),
    ]
